// <auto-generated />
using System;
using AspNetCore31Test2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCore31Test2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200415170631_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCore31Test2.Models.Entity1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entity1s");
                });

            modelBuilder.Entity("AspNetCore31Test2.Models.Entity2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Entity1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Entity1Id")
                        .IsUnique();

                    b.ToTable("Entity2s");
                });

            modelBuilder.Entity("AspNetCore31Test2.Models.Entity3", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Entity2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Entity2Id")
                        .IsUnique();

                    b.ToTable("Entity3s");
                });

            modelBuilder.Entity("AspNetCore31Test2.Models.Entity2", b =>
                {
                    b.HasOne("AspNetCore31Test2.Models.Entity1", "Entity1")
                        .WithOne("Entity2")
                        .HasForeignKey("AspNetCore31Test2.Models.Entity2", "Entity1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCore31Test2.Models.Entity3", b =>
                {
                    b.HasOne("AspNetCore31Test2.Models.Entity2", "Entity2")
                        .WithOne("Entity3")
                        .HasForeignKey("AspNetCore31Test2.Models.Entity3", "Entity2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
